baseURL = "https://example.com/"
languageCode = "en-us"
title = "Ukiyoe Streams"
paginate = 10
enableRobotsTXT = true
[params]
  description = "Floating world of streaming"
  author = "Ukiyoe Streams Team"
[outputs]
  home = ["HTML", "RSS"]
[sitemap]
  changefreq = "daily"
  priority = 0.8
[markup.goldmark.renderer]
  unsafe = true
